name: Docker Dev Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Docker build
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/lynx-iberian:$(date +%Y.%m)-dev
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/lynx-iberian:$(date +%Y.%m)-dev
